# Before editing this file please read documentation - https://github.com/sasstools/sass-lint/tree/master/docs
# Please pay attention that in some cases, those hints will help you without editing
# the config file - https://github.com/sasstools/sass-lint/blob/master/docs/toggle-rules-in-src.md

# SASSLint Options
options:
  formatter: stylish
  merge-default-rules: false
files:
  include: "**/scss/**/*.s+(a|c)ss"
  ignore:
    - "node_modules/**/*.scss"
    - "**/scss/libraries/**/*.*"
    - "**/static/styleguide/**/*.*"

# SASSLint Rules
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth:
    - 1
    - max-depth: 1
  border-zero:
    - 2
    - convention: 0
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
    - allow-leading-underscore: false
  declarations-before-nesting: 2
  empty-args:
    - 2
    - include: true
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: ^[a-z\d_-]+$
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - convention: camelcase
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  max-line-length:
    - 2
    - length: 120
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 2
    - exclude: [
        'grid-breakpoint-down',
        'grid-breakpoint-up',
        'grid-breakpoint-between',
        'grid-breakpoint-only',
        'grid-breakpoint',
        'on-event',
        'when-inside'
    ]
  nesting-depth:
    - 2
    - max-depth: 3
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-map-identifiers: true
      allow-rgba: true
      allow-variable-identifiers: true
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols:
    - 2
    - allow-protocol-relative-urls: true
  no-vendor-prefixes:
    - 2
    - additional-identifiers: []
      excluded-identifiers: ["webkit"]
      ignore-non-standard: true
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
  property-sort-order:
    - 2
    - order: alphabetical
    - ignore-custom-properties: false
  property-units:
    - 2
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - "%"
      per-property: {}
  pseudo-element: 2
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 0
    - properties: []
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: ^[a-zA-Z\d_-]+$
  zero-unit: 2
